# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0002_auto_20170108_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='zniżka'),
        ),
    ]
