# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0003_attendees_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='czas rejestracji'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='dzień zajęć'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('attendee', 'training', 'date')]),
        ),
    ]
