# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0005_auto_20170122_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='e-mail'),
        ),
    ]
