# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttapp', '0006_attendees_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendees',
            name='exam',
            field=models.BooleanField(default=False, verbose_name='Opłacony egzamin'),
        ),
        migrations.AddField(
            model_name='attendees',
            name='extra',
            field=models.BooleanField(default=True, verbose_name='Dodatkowe płatności'),
        ),
        migrations.AddField(
            model_name='attendees',
            name='seminar',
            field=models.BooleanField(default=False, verbose_name='Opłacony staż'),
        ),
    ]
